name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Xterm.js yükle
      run: |
       sudo apt-get update
       sudo apt-get install --install-recommends nodejs npm git -y
       mkdir DEDEm
       cd DEDEm
       npm install xterm xterm-addon-attach xterm-addon-fit xterm-addon-search xterm-addon-web-links
       git add -A
       git commit -m "xterm.js Yükle"
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
